Repository the-events-calendar/product-taskmaster, pull requests merged in 2021-06, with the labels that each got.

#43 Add eslint configurations
  .stylelintignore
  .stylelintrc
  config/eslint.es5.js
  config/eslint.es6.js
  config/eslint.react.js
  package-lock.json
  package.json
  tasks/eslint.js
Labels: merge

#44 Set filePath flag for stylelint task
  index.js
  tasks/compress-js.js
  tasks/eslint.js
  tasks/package.js
  tasks/stylelint.js
Labels: code review

#45 update package json version
  package-lock.json
  package.json
Labels: code review

#46 update readme version to 1.2.0
  README.md
Labels: code review

#47 add readme entry for eslint, update stylelint readme
  README.md
Labels: code review

#48 Update package version to 1.2.1
  README.md
  package-lock.json
  package.json
Labels: code review

#49 Fix eslint parser
  README.md
  config/eslint.es6.js
  package-lock.json
  package.json
Labels: code review

#50 update version to 1.2.2
  package-lock.json
  package.json
Labels: code review

#32 Feature/customizer phase 4 - Change postcss to "preserve" to use CSS custom props
  .gitignore
  README.md
  tasks/postcss.js
  tasks/watch.js
Labels: code review, needs release

#51 Update version to 1.3.0
  README.md
  package-lock.json
  package.json
Labels: merge
