Repository the-events-calendar/product-taskmaster, pull requests merged in 2021-05, with the labels that each got.

#36 Setup repo for npm publish
  README.md
  package-lock.json
  package.json
Labels: code review

#38 Make sure "events-pro" is converted into a valid variable.
  webpack/externals/tribe/events-pro.js
Labels: code review, merge

#40 Update gulp stylelint and stylelint to latest versions
  package-lock.json
  package.json
Labels: merge

#41 Add stylelint configuration
  README.md
  config/stylelint.js
  package-lock.json
  package.json
Labels: merge

#42 Update version to 1.1.0
  README.md
  package-lock.json
  package.json
Labels: code review
